const teams=[
 {code:'GB',name:'Gənclərbirliyi',group:'A',logo:'genclerbirliyi.png'},
 {code:'QRT',name:'Qurtuluş',group:'A',logo:'qurtulus.png'},
 {code:'SİY',name:'Siyəzən',group:'A',logo:'siyezen.png'},
 {code:'KMN',name:'Komando Sumqayıt',group:'A',logo:'komando.png'},
 {code:'FVS',name:'Five Star',group:'B',logo:'five-star.png'},
 {code:'AGT',name:'Agrotam',group:'B',logo:'agrotam.png'},
 {code:'OMN',name:'Old Men',group:'B',logo:'old-men.png'},
 {code:'ƏRT',name:'Ərtoğrul',group:'B',logo:'ertogrul.png'}
];
const teamByCode=Object.fromEntries(teams.map(t=>[t.code,t]));
// Round scores and match details are transcribed from the league organizer's supplied data.
const matches=[
 {r:1,date:'5 sentyabr 2026',time:'20:00',home:'AGT',away:'OMN',hs:4,as:3,venue:'Azfar',best:'Fərid Abbasov',scorers:['Orxan Quliyev','Müğdət İbrahimli','Ədalət Qafarlı','Fərid Abbasov','Kənan İbişov','Kənan İbişov','Mirzəxan Bəyalızadə'],cards:6},
 {r:1,date:'5 sentyabr 2026',time:'21:00',home:'QRT',away:'KMN',hs:4,as:0,venue:'Azfar',best:'Yusif Rufullazadə',scorers:['Yusif Rufullazadə','Məhəmməd Hüseynov','Ramiz Hacıyev','Məhəmməd Xəlilov'],cards:3},
 {r:1,date:'6 sentyabr 2026',time:'13:00',home:'FVS',away:'ƏRT',hs:5,as:2,venue:'Azfar',best:'Əsgər Abbasov',scorers:['Əsgər Abbasov','Nicat Məhərrəmov','Emil Abbaszadə','Emil Abbaszadə','Vahid Həsənov','İlkin Vəlizadə','Mətin Mehtiyev'],cards:4},
 {r:1,date:'6 sentyabr 2026',time:'14:00',home:'GB',away:'SİY',hs:5,as:3,venue:'Azfar',best:'Məhəmməd Alıyev',scorers:['Məhəmməd Alıyev','Məhəmməd Alıyev','Məhəmməd Alıyev','Elnur Hüseynov','Mirzə Əmirov','Cavad Həsənov','Cavad Həsənov','Təbriz Yahyayev'],cards:0},
 {r:2,date:'13 sentyabr 2026',time:'14:00',home:'SİY',away:'QRT',hs:3,as:4,venue:'Azfar',best:'Ramiz Hacıyev',scorers:['Xalid Muradzadə','Hacbala Mayılov','Rövşən Ələsgərov','Ramiz Hacıyev','Ramiz Hacıyev','Ramiz Hacıyev','Yusif Rufullazadə'],cards:1},
 {r:2,date:'13 sentyabr 2026',time:'15:00',home:'FVS',away:'OMN',hs:5,as:1,venue:'Azfar',best:'Nazim Baxşıyev',scorers:['Nicat Məhərrəmov','Nicat Məhərrəmov','Kənan Sultanov','Nazim Baxşıyev','Vahid Həsənov','Tahir Kərimov'],cards:1},
 {r:2,date:'13 sentyabr 2026',time:'16:00',home:'GB',away:'KMN',hs:6,as:3,venue:'Azfar',best:'Elnur Hüseynov',scorers:['Elnur Hüseynov','Elnur Hüseynov','Elnur Hüseynov','Mirzə Əmirov','Məhmməd Nəsibov','Məhəmməd Alıyev','Fərid Muxtarov','Murad Zamanlı','İbrahim Tahirov'],cards:1},
 {r:2,date:'13 sentyabr 2026',time:'17:00',home:'ƏRT',away:'AGT',hs:4,as:2,venue:'Azfar',best:'Alim Qafarlı',scorers:['Samir Əmirxanov','Samir Əmirxanov','Alim Qafarlı','Elnur Soltanlı','Sahil Əsgərli','Dəniz Əsgərli'],cards:1},
 {r:3,date:'20 sentyabr 2026',time:'14:00',home:'KMN',away:'SİY',hs:3,as:4,venue:'Azfar',best:'Rövşən Ələsgərov',scorers:['Fərid Muxtarov','İbrahim Tahirov','İsmayıl Hüseynli','Yusif Kərimov','Rövşən Ələsgərov','Təbriz Yahyayev'],cards:0},
 {r:3,date:'20 sentyabr 2026',time:'15:00',home:'FVS',away:'AGT',hs:3,as:4,venue:'Azfar',best:'Fərid Salahov',scorers:['Əsgər Abbasov','Nicat Məhərrəmov','Əsgər Abbasov','Fərid Salahov','Sahil Əsgərli','Məhəmməd Hacıyev'],cards:6},
 {r:3,date:'20 sentyabr 2026',time:'16:00',home:'GB',away:'QRT',hs:2,as:5,venue:'Azfar',best:'Məhəmməd Xəlilov',scorers:['Elnur Hüseynov','Elnur Hüseynov','Ramiz Hacıyev','Məhəmməd Xəlilov','Məhəmməd Xəlilov','Vüsal Buludlu','Rauf İbrahimli'],cards:2},
 {r:3,date:'20 sentyabr 2026',time:'17:00',home:'OMN',away:'ƏRT',hs:3,as:2,venue:'Azfar',best:'David Əhmədov',scorers:['Anar Muradov','Kənan İbişov','Anar Muradov','Alim Qafarlı','Nicat Məmmədov'],cards:2},
 {r:4,date:'27 sentyabr 2026',time:'14:00',home:'SİY',away:'GB',hs:7,as:2,venue:'Azfar',best:'Rövşən Ələsgərov',scorers:['Yusif Kərimov','Qüvvət Əmrahov','Rövşən Ələsgərov','Cavid Həşimov','Rövşən Ələsgərov','Cavid Həşimov','Rövşən Ələsgərov','Təbriz Yahyayev','Rövşən Ələsgərov'],cards:1},
 {r:4,date:'27 sentyabr 2026',time:'15:00',home:'OMN',away:'AGT',hs:3,as:5,venue:'Azfar',best:'Məhəmməd Hacıyev',scorers:['Məhəmməd Hacıyev','Anar Muradov','Məhəmməd Hacıyev','Fərid Salahov','Sahil Əsgərli','Müğdət İbrahimli','Anar Muradov','Kənan İbişov'],cards:2},
 {r:4,date:'27 sentyabr 2026',time:'16:00',home:'KMN',away:'QRT',hs:3,as:3,venue:'Azfar',best:'Yusif Rufullazadə',scorers:['Yusif Rufullazadə','Murad Zamanlı','Ramiz Hacıyev','Məhəmməd Xəlilov','Fərid Muxtarov','Cəmil İbrahimov'],cards:3},
 {r:4,date:'27 sentyabr 2026',time:'17:00',home:'ƏRT',away:'FVS',hs:2,as:5,venue:'Azfar',best:'Səxavət Pirmuradov',scorers:['Mətin Mehtiyev','Kamran Hüseynov','Zakir Rəşidov','Əsgər Abbasov','Səxavət Pirmuradov','Səxavət Pirmuradov','Natiq Kərimov'],cards:0},
 {r:5,date:'4 oktyabr 2026',time:'14:00',home:'QRT',away:'SİY',hs:1,as:6,venue:'Azfar',best:'Cavad Həsənov',scorers:['Cavad Həsənov','Cavad Həsənov','Natiq İsmayılzadə','Yusif Kərimov','Təbriz Yahyayev','Cavad Həsənov','Rövşən Ələsgərov'],cards:2},
 {r:5,date:'4 oktyabr 2026',time:'15:00',home:'AGT',away:'ƏRT',hs:2,as:4,venue:'Azfar',best:'',scorers:['Fərid Abbasov','Elnur Soltanlı','Kamran Hüseynov','Elnur Soltanlı','Elşən Babayev','Alim Qafarlı'],cards:2},
 {r:5,date:'4 oktyabr 2026',time:'16:00',home:'KMN',away:'GB',hs:1,as:4,venue:'Azfar',best:'Məhəmməd Nəsibov',scorers:['Nurlan Bayramov','Fərid Muxtarov','Nurlan Bayramov','Elnur Hüseynov','Elnur Hüseynov'],cards:2},
 {r:5,date:'4 oktyabr 2026',time:'17:00',home:'OMN',away:'FVS',hs:1,as:4,venue:'Azfar',best:'Emil Abbaszadə',scorers:['Mirzəxan Bəyalızadə','Emil Abbaszadə','Nicat Məhərrəmov','Kənan Tanriverdiyev','Afər Quliyev'],cards:1},
 {r:6,date:'11 oktyabr 2026',time:'14:00',home:'SİY',away:'KMN',venue:'Azfar'},
 {r:6,date:'11 oktyabr 2026',time:'15:00',home:'ƏRT',away:'OMN',venue:'Azfar'},
 {r:6,date:'11 oktyabr 2026',time:'16:00',home:'QRT',away:'GB',venue:'Azfar'},
 {r:6,date:'11 oktyabr 2026',time:'17:00',home:'AGT',away:'FVS',venue:'Azfar'}
];
const standings={A:[['QRT',5,3,1,1,17,14,3,10],['SİY',5,3,0,2,23,15,8,9],['GB',5,3,0,2,19,19,0,9],['KMN',5,0,1,4,10,21,-11,1]],B:[['FVS',5,4,0,1,22,10,12,12],['AGT',5,3,0,2,17,17,0,9],['ƏRT',5,2,0,3,14,17,-3,6],['OMN',5,1,0,4,11,20,-9,3]]};
const scorers=[['GB','Elnur Hüseynov',8],['SİY','Rövşən Ələsgərov',7],['QRT','Ramiz Hacıyev',6],['FVS','Nicat Məhərrəmov',5],['SİY','Cavad Həsənov',5],['GB','Məhəmməd Alıyev',4],['QRT','Məhəmməd Xəlilov',4],['KMN','Fərid Muxtarov',4],['FVS','Əsgər Abbasov',4],['OMN','Kənan İbişov',4],['OMN','Anar Muradov',4],['SİY','Təbriz Yahyayev',4],['QRT','Yusif Rufullazadə',3],['FVS','Emil Abbaszadə',3],['AGT','Məhəmməd Hacıyev',3],['AGT','Sahil Əsgərli',3],['SİY','Yusif Kərimov',3],['ƏRT','Elnur Soltanlı',3],['ƏRT','Alim Qafarlı',3],['GB','Cavid Həşimov',2],['GB','Mirzə Əmirov',2],['GB','Nurlan Bayramov',2],['KMN','İbrahim Tahirov',2],['KMN','Murad Zamanlı',2],['FVS','Səxavət Pirmuradov',2],['AGT','Fərid Salahov',2],['AGT','Müğdət İbrahimli',2],['AGT','Fərid Abbasov',2],['OMN','Mirzəxan Bəyalızadə',2],['ƏRT','Mətin Mehtiyev',2],['ƏRT','Kamran Hüseynov',2],['ƏRT','Samir Əmirxanov',2],['GB','Məhmməd Nəsibov',1],['QRT','Natiq İsmayılzadə',1],['QRT','Məhəmməd Hüseynov',1],['QRT','Vüsal Buludlu',1],['QRT','Rauf İbrahimli',1],['KMN','İsmayıl Hüseynli',1],['KMN','Cəmil İbrahimov',1],['FVS','Kənan Tanriverdiyev',1],['FVS','Nazim Baxşıyev',1],['FVS','Kənan Sultanov',1],['FVS','Natiq Kərimov',1],['AGT','Ədalət Qafarlı',1],['AGT','Orxan Quliyev',1],['AGT','Dəniz Əsgərli',1],['OMN','Tahir Kərimov',1],['SİY','Xalid Muradzadə',1],['SİY','Hacbala Mayılov',1],['SİY','Qüvvət Əmrahov',1],['ƏRT','İlkin Vəlizadə',1],['ƏRT','Nicat Məmmədov',1]];
function logo(code){return 'assets/'+teamByCode[code].logo}function score(m){return m.hs===undefined?'VS':`${m.hs} – ${m.as}`}function dateShort(s){return s.replace(' sentyabr ',' SEN ').replace(' oktyabr ',' OKT ').toUpperCase()}
function renderMatches(round='all'){let arr=matches.filter(m=>round==='all'||m.r===Number(round));document.querySelector('#match-list').innerHTML=arr.map(m=>{let h=teamByCode[m.home],a=teamByCode[m.away],done=m.hs!==undefined;return `<article class="match-card"><div class="match-card-top"><span>${m.r}-Cİ TUR · ${dateShort(m.date)} · ${m.time}</span><span class="status ${done?'':'upcoming'}">${done?'TAMAMLANIB':'PLANLAŞDIRILIB'}</span></div><div class="match-pair"><div class="match-side"><img src="${logo(h.code)}" alt=""><span>${h.name}</span></div><div class="match-score ${done?'':'upcoming'}">${score(m)}</div><div class="match-side"><span>${a.name}</span><img src="${logo(a.code)}" alt=""></div></div><div class="match-meta"><span>⌖ <b>${m.venue}</b></span><span>${done?(m.best?'Ən yaxşı: '+m.best:'Yekun hesab'):'Başlama saatı: '+m.time}</span></div></article>`}).join('')||'<div class="no-results">Bu tur üçün oyun tapılmadı.</div>'}
function renderTable(group='A'){document.querySelector('#table-title').textContent='QRUP '+group;document.querySelector('#table-body').innerHTML=standings[group].map((r,i)=>{let t=teamByCode[r[0]];return `<tr><td>${String(i+1).padStart(2,'0')}</td><td><div class="team-cell"><img src="${logo(t.code)}" alt=""><span>${t.name}</span></div></td>${r.slice(1,8).map(v=>`<td>${v>0&&v!==r[1]?v:v}</td>`).join('')}<td class="points">${r[8]}</td></tr>`}).join('')}
function renderTeams(){document.querySelector('#team-grid').innerHTML=teams.map(t=>`<article class="team-card" data-code="${t.code}"><div class="team-card-top"><img src="${logo(t.code)}" alt="${t.name} loqosu"><span class="team-code">${t.code}</span></div><h3>${t.name}</h3><p>2026 / 27 mövsümü</p><span class="team-group">QRUP ${t.group}</span></article>`).join('')}
function renderScorers(){const q=document.querySelector('#scorer-search').value.trim().toLocaleLowerCase('az'),f=document.querySelector('#team-filter').value;const arr=scorers.filter(s=>(f==='all'||s[0]===f)&&(`${s[1]} ${teamByCode[s[0]].name}`).toLocaleLowerCase('az').includes(q));document.querySelector('#scorer-body').innerHTML=arr.map(s=>{let t=teamByCode[s[0]];return `<tr><td>${scorers.indexOf(s)+1}</td><td>${s[1]}</td><td><span class="scorer-team"><img src="${logo(t.code)}" alt="">${t.name}</span></td><td>${s[2]}</td></tr>`}).join('')||'<tr><td colspan="4" class="scorer-empty">Axtarışa uyğun oyunçu tapılmadı.</td></tr>'}
document.querySelectorAll('[data-round]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-round]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMatches(b.dataset.round)}));document.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-group]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTable(b.dataset.group)}));document.querySelector('#scorer-search').addEventListener('input',renderScorers);document.querySelector('#team-filter').innerHTML+=[...teams].map(t=>`<option value="${t.code}">${t.name}</option>`).join('');document.querySelector('#team-filter').addEventListener('change',renderScorers);document.querySelector('#hamb').addEventListener('click',()=>document.querySelector('#navlinks').classList.toggle('open'));document.querySelectorAll('#navlinks a').forEach(a=>a.addEventListener('click',()=>document.querySelector('#navlinks').classList.remove('open')));renderMatches();renderTable();renderTeams();renderScorers();
